name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: powershell
        npm run-script build
    - name: Deploy
      uses: prabhumk3/jsonmodel
      with:
        BRANCH: gh-pages
        FOLDER: build
