name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_TOKEN:${{ env.REACT_APP_TOKEN_VALUE }}
    - name: Deploy
      uses: prabhumk3/jsonmodel
      with:
        GITHUB_TOKEN: ${{ env.REACT_APP_TOKEN_VALUE }}
        BRANCH: gh-pages
        FOLDER: build
