name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    -  shell: bash
       env:
        SUPER_SECRET: ${{ secrets.SuperSecret }}
       run: |
        example-command "$SUPER_SECRET"
        
    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_TOKEN:${{ secrets.REACT_APP_TOKEN_VALUE }}
    - name: Deploy
      uses: prabhumk3/jsonmodel
      with:
        GITHUB_TOKEN: ${{ secrets.REACT_APP_TOKEN_VALUE }}
        BRANCH: gh-pages
        FOLDER: build
