name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run-script build
    - name: Deploy
      uses: prabhumk3/jsonmodel
      with:
        GITHUB_TOKEN: ${{ secrets.REACT_APP_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
