name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/master

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_TOKEN:${{ secrets.REACT_APP_TOKEN }}
    - name: Deploy
      uses: prabhumk3/jsonmodel@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.REACT_APP_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
